-- Proposals with line items; contracts created when a proposal is accepted.

create table public.proposal (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.client (id) on delete cascade,
  title text not null default '',
  status text not null default 'draft'
    check (
      status in (
        'draft',
        'sent',
        'pending',
        'accepted',
        'declined',
        'expired'
      )
    ),
  proposal_number int generated by default as identity unique not null,
  issued_at date not null default (current_date),
  valid_until date,
  discount_amount numeric(12, 2) not null default 0,
  notes text,
  payment_instructions text,
  billing_snapshot jsonb not null default '{}'::jsonb,
  agency_snapshot jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index proposal_client_id_idx on public.proposal (client_id);
create index proposal_status_idx on public.proposal (status);
create index proposal_updated_at_idx on public.proposal (updated_at desc);

create table public.proposal_line_item (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references public.proposal (id) on delete cascade,
  description text not null default '',
  quantity numeric(12, 4) not null default 1
    check (quantity >= 0),
  unit_price numeric(12, 2) not null default 0
    check (unit_price >= 0),
  line_total numeric(12, 2) generated always as (quantity * unit_price) stored,
  sort_order int not null default 0
);

create index proposal_line_item_proposal_id_idx
  on public.proposal_line_item (proposal_id, sort_order);

create table public.contract (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null unique references public.proposal (id) on delete cascade,
  status text not null default 'draft'
    check (status in ('draft', 'sent', 'signed')),
  terms_snapshot text,
  signed_at timestamptz,
  signer_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index contract_proposal_id_idx on public.contract (proposal_id);

alter table public.proposal enable row level security;
alter table public.proposal_line_item enable row level security;
alter table public.contract enable row level security;

create policy "agency_all_proposal"
  on public.proposal for all
  using (public.is_agency_staff())
  with check (public.is_agency_staff());

create policy "agency_all_proposal_line_item"
  on public.proposal_line_item for all
  using (public.is_agency_staff())
  with check (public.is_agency_staff());

create policy "agency_all_contract"
  on public.contract for all
  using (public.is_agency_staff())
  with check (public.is_agency_staff());

-- Atomic accept: set proposal accepted + ensure one contract row.
create or replace function public.accept_proposal(p_proposal_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  cid uuid;
  terms text;
  st text;
begin
  if auth.uid() is null or not public.is_agency_staff() then
    raise exception 'forbidden';
  end if;

  select status, coalesce(notes, '')
  into st, terms
  from public.proposal
  where id = p_proposal_id
  for update;

  if st is null then
    raise exception 'not_found';
  end if;

  if st = 'accepted' then
    select c.id into cid
    from public.contract c
    where c.proposal_id = p_proposal_id;
    if cid is null then
      insert into public.contract (proposal_id, status, terms_snapshot)
      values (p_proposal_id, 'draft', nullif(trim(terms), ''))
      returning id into cid;
    end if;
    return cid;
  end if;

  if st not in ('draft', 'sent', 'pending') then
    raise exception 'invalid_status';
  end if;

  update public.proposal
  set status = 'accepted', updated_at = now()
  where id = p_proposal_id;

  insert into public.contract (proposal_id, status, terms_snapshot)
  values (p_proposal_id, 'draft', nullif(trim(terms), ''))
  on conflict (proposal_id) do nothing
  returning id into cid;

  if cid is null then
    select c.id into cid
    from public.contract c
    where c.proposal_id = p_proposal_id;
  end if;

  return cid;
end;
$$;

grant execute on function public.accept_proposal(uuid) to authenticated;
